version: "3"

services:
  redis:
    image: redis
    restart: always
    environment:
      - MONGO_ADDRESS=mongo
      - APP_PATH=/app
    volumes:
      - redisdata:/data
    ports:
      - "6379:6379"

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodata:
  redisdata: